### ISSUE TITLE
[NSFW] Pornhub

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#100]
### Source name

Pornhub

### Source URL

https://www.pornhub.com

### Package type

bangumi

### Source language

en

### Other details

Reference: https://github.com/bachig26/porn-cli/blob/main/porn_cli/websites/porn/pornhub.py

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Big NO, they are fast in giving DMCA + web protection against scraping.
