### ISSUE TITLE
[NSFW] 야동코리아 YADONGKOREA

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#104]
### Source name

야동코리아 YADONGKOREA

### Source URL

https://yadongkorea.org

### Package type

bangumi

### Source language

kr

### Other details

@OshekharO i'm opening some for different range/ this is last of my nsfw request.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Bad luck 😞, cloudflare protection is there.

**Comment by bachig26** [comment]
> Bad luck 😞, cloudflare protection is there.

Ohhh...☹️
