### ISSUE TITLE
JavHD: 404 not found host issue

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#105]
### Extension information

JavHD

### Steps to reproduce

1. open JavHD in search
2. look for the title `SDDE-706` in the list or by searching
3. then error attached will appear.

### Miru version

1.7.2

### Other details

@OshekharO i have provided the `Debug log` from vlc. there seems to a problem with the host but it works via browser, not sure if it's due to different server in webpage.

[sdde-706.txt](https://github.com/miru-project/repo/files/13258864/sdde-706.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Ahh it's an issue from the hosting itself not an issue from extension. Check the specific video on website it's saying error video cannot be played.
