### ISSUE TITLE
sflix.to, 9animetv.to, flixhq.to: enimax-anime/key dmca'd

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#108]
### Extension information

sFlix | 9Anime | Flixhq

### Miru version

1.7.2

### Other details

@appdevelpo since most of the enimax-anime's repo have been dmca'd yesterday (07/11/2023) and he removed the every repo's related to that.
and the key repo also gone, the both of extensions mentioned here doesn't work.

can you able to fix them, and for an alternative to it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by bachig26** [comment]
@OshekharO flixhq.to extension also gone since consumet api uses the key for this site too.

**Comment by bachig26** [comment]
@appdevelpo @OshekharO keys are available here: https://github.com/theonlymo/keys | https://github.com/Claudemirovsky/keys

**Comment by appdevelpo** [comment]
9anime and sflix has been update.You can have a try.

**Comment by bachig26** [comment]
i'm closing this issue as the extensions haven been fixed.
