### ISSUE TITLE
哔嘀影视（简称BDYS): CN Torrent

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#111]
### Source name

哔嘀影视 BDYS

### Source URL

https://www.bdys10.com | current main domain

### Package type

bangumi

### Source language

zh-cn

### Other details

Info Domain of BDYS (for new domains/DNS Updates): https://www.bdys.me

This site has all chinese and asian contents in 1080p & + that I use when it's not available in other cloud host streaming sites.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
I almost completed whole extension, then later on I knew that there is captcha issue in search 🤷. Please check before recommending. It was a good site through.
