### ISSUE TITLE
DramaCool: video doesn't play, possible issue with api and domain

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#120]
### Extension information

DramaCool

### Miru version

1.7.2

### Other details

@OshekharO please have a look at this issue. I saw that the domain has been change few (~couple) days back.
also it looks like the api hasn't been updated for DramaCool and there may be some other changes needed.

furthermore, you can view the search page, detail page but the video player opens and doesn't play anything.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Infact evrything is okay from my side, it's consumet api issue.

**Comment by bachig26** [comment]
> Infact evrything is okay from my side, it's consumet api issue.

is it possible to rewrite the extension by fetching the content directly from the website similar to other extensions to avoid this issues?

**Comment by bachig26** [comment]
@OshekharO #121 GoGoAnime also doesn't work as of today, as it couldn't even fetch the latest page as DramaCool do.
currently, both extension are out.
