### ISSUE TITLE
make a tutorial on how to use this app

### ISSUE THREAD

**Issue by MrConqueror** [miru-project/repo#126]
### Extension information

.

### Steps to reproduce

.

### Miru version

.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
1. Download the application from GitHub repo.
2. Install the downloaded application.
3. Open the application-> Goto Extensions -> Repository -> start installing.
4. Now Goto Search and enjoy 😄
