### ISSUE TITLE
gimy.ai 

### ISSUE THREAD

**Issue by Joackk** [miru-project/repo#128]
### Source name

gimy

### Source URL

https://gimy.ai/

### Package type

bangumi

### Source language

zh

### Other details

用原仓库的gimy偶尔会卡顿所以想去官网看看时候搜到的，试了下似乎速度更快，而且长得也一样

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Is your problem fixed? @Joackk

**Comment by Joackk** [comment]
> Is your problem fixed? @Joackk

It seems not yet, I didn't see it in the repository.

**Comment by OshekharO** [comment]
https://github.com/miru-project/repo/blob/main/repo/gimy.su.js

This is same right?

**Comment by Joackk** [comment]
> https://github.com/miru-project/repo/blob/main/repo/gimy.su.js
> 
> This is same right?

They seem to be the same, but they are not. I think they should be based on a framework, but there are some subtle differences, I have tried to apply directly to the existing one, but the element calls are different. Because I know too little about this part, I can't succeed

**Comment by appdevelpo** [comment]
> > https://github.com/miru-project/repo/blob/main/repo/gimy.su.js
> > This is same right?
> 
> They seem to be the same, but they are not. I think they should be based on a framework, but there are some subtle differences, I have tried to apply directly to the existing one, but the element calls are different. Because I know too little about this part, I can't succeed

我剛剛加了 gimy.ai 在 gimy 裡，解密的部分因為遇不到加密連結所以沒有測試，可以去試試。

**Comment by Joackk** [comment]
@appdevelpo 仓库里的那个gimy吗？仓库里的提示给我
![image](https://github.com/miru-project/repo/assets/45162558/382e2aaf-54bc-4262-a9dc-6fa5f908c48e)

**Comment by appdevelpo** [comment]
我剛pr一個

**Comment by Joackk** [comment]
> 我剛pr一個

估计还在审核，现在仓库里看不到

**Comment by appdevelpo** [comment]
倉庫裡有了

**Comment by Joackk** [comment]
> 倉庫裡有了

是那个？没有看到新的gimy啊

**Comment by appdevelpo** [comment]
舊的更新v0.0.2

**Comment by Joackk** [comment]
> 舊的更新v0.0.2

可以正常使用
