### ISSUE TITLE
add website uptime/availability checker

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#133]
### Source name

.

### Source URL

.

### Package type

.

### Source language

.

### Other details

possibly an additional column in readme that indicates if the extensions website is available or not.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Infact it should be more like cloudstream like an extension is broken but currently I don't have time to fix it so I just added 0

     * Status int as the following:
     * 0: Down
     * 1: Ok

In 

// ==MiruExtension==
// @name         9Anime
// @status         1

Adding 0 should hide the extension from application warehouse and when I change 0 to 1 in repo it should show the extension.
