### ISSUE TITLE
[sflix] detail page can't be displayed ~ 'cannot read property 'map' of null at detail'

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#143]
### Extension information

sFlix

### Steps to reproduce

1. go to 'search' in sflix
2. search 'hooten & the lady'
3. open the title 'hooten & the lady' from the search result
4. then the error appears

### Miru version

1.7.2

### Other details

![miru_4IZtspgc1S](https://github.com/miru-project/repo/assets/96393348/fe4c7472-c883-46a9-aabb-ab890b5482fb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by appdevelpo** [comment]
have you tried to access the link? 
https://sflix.to/ajax/season/episodes/17789
and then you look up https://sflix.to/tv/free-hooten-and-the-lady-hd-36181
You'll find there's nothing there.
so the result is null

**Comment by bachig26** [comment]
> have you tried to access the link? 
> 
> https://sflix.to/ajax/season/episodes/17789
> 
> and then you look up https://sflix.to/tv/free-hooten-and-the-lady-hd-36181
> 
> You'll find there's nothing there.
> 
> so the result is null 

Oh okay, I was using fmovies in the browser and didn't check the sflix as I only it for miru, since this is the only proper English extension.

**Comment by 0xDkXy** [comment]
But I encountered the same problem when watching The Big Bang Theory on the sFlix on the Miru.

![Screenshot_20240213-005457_Miru](https://github.com/miru-project/repo/assets/55947248/39cd5ca0-4ae5-4e30-9760-5d33f5415d28)

But the TBBT on the sFlix do have episodes.
