### ISSUE TITLE
[more m3u8 support] MyIPTV ~ not an issue report

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#154]
### Extension information

MyIPTV

### Miru version

-

### Other details

@vvsolo please have a look at these iptv streams, see if you can add them.

strm2hls: https://github.com/azgaresncf/strm2hls
Subir-Max: https://github.com/subirkumarpaul/Subir-Max
Utube (YT News Channels): https://github.com/pshanmu3/Utube
https://github.com/fifaivan/TV

https://github.com/Buddyalfian25/nontons (i'm not sure, but found on my random search, might be useful).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by vvsolo** [comment]
@bachig26 
0.0.4 update:
built-in source change add online json format sources
[MyIPTV-sources](https://github.com/vvsolo/miru-extension-MyIPTV-sources/blob/main/sources.json)
you can repo

also, you provide a few of the encryption or formats invalid
