### ISSUE TITLE
Kisskh: need decryption for subtitles (i think)

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#164]
### Extension information

Kisskh

### Steps to reproduce

1. open 'Hidden Love' tv series
2. select 'English' subtitle
3. you can see the subtitle looks like encrypted format

### Miru version

1.7.2

### Other details

@OshekharO 
![miru_6HSxTJ6e2p](https://github.com/miru-project/repo/assets/96393348/b2615549-9c9c-4860-bd3e-c8adcce7d085)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Well I don't have experience with key based decryption. 

https://github.com/aniyomiorg/aniyomi-extensions/blob/master/src/en/kisskh/src/eu/kanade/tachiyomi/animeextension/en/kisskh/SubDecryptor.kt

https://kisskh.co/api/Sub/129692

@appdevelpo

**Comment by appdevelpo** [comment]
I don't think currently we have any method to let it works in miru even though we have their key and decrypting method. It need to pass through an url to reach the app.
