### ISSUE TITLE
Add this extension of novel in pt-br

### ISSUE THREAD

**Issue by maryhannah2** [miru-project/repo#168]
### Source name

Central Novel

### Source URL

https://centralnovel.com

### Package type

novel

### Source language

PT-BR

### Other details

This is a site for translating novels into Brazilian Portuguese.
If possible, add extensions in other languages, such as Brazilian Portuguese.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Error establishing a database connection
