### ISSUE TITLE
KimCartoon broken for sometime now

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#172]
### Extension information

KimCartoon

### Miru version

1.8.0

### Other details

i think they might have changed the html classes. 🤔

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
I will see when I get time.

Edit: just tried opening the site taking too long, probably site issue.

**Comment by OshekharO** [comment]
Fixed by itself.
