### ISSUE TITLE
couple of change request to Kisskh

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#186]
### Extension information

Kisskh

### Miru version

1.8.1

### Other details

1. currently the `Latest page in miru` for Kisskh extension is set to `https://kisskh.co/api/DramaList/List?page=$%7Bpage%7D&type=0&sub=0&country=0&status=0&order=1&pageSize=40`, i would to ask if it's possible to change to this page `Latest Updates` of Kisskh `https://kisskh.co/Explore?order=2`? _(i don't know the location based api)_

2. by default with Kisskh search function, it shows the result only when the 1st word matches with their catalogue, is it possible to make something with extension search to fetch the result even if the word is not a 1st one.
for example of current Kisskh: the C-Drama titled `Amidst a Snowstorm of Love`, when searching with the term "Snowstrom" the result is "not found", need to use the term "Amidst" to see the result appear.
@OshekharO 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
![Screenshot_20240202-220242_Miru](https://github.com/miru-project/repo/assets/95137948/6faa2394-fc7d-4c92-87ac-717b2de94388)

Search is working fine.

**Comment by bachig26** [comment]
> Search is working fine.

that's really weird.

![vivaldi_chBkYAFOIe](https://github.com/miru-project/repo/assets/96393348/65aa3ba9-cc49-41fb-828c-adb2368d1201)

![vivaldi_aGcEu4UrrU](https://github.com/miru-project/repo/assets/96393348/72d047dd-8cbd-4309-b337-8f225f17d219)

**Comment by OshekharO** [comment]
No idea I tried with 2 devices it's working perfect from my side as for 1st request have made changes.
