### ISSUE TITLE
Comick Extension Error 403

### ISSUE THREAD

**Issue by AdalynBlack** [miru-project/repo#190]
### Extension information

Comick v0.0.4

### Steps to reproduce

1. Install the Comick extension
2. Go to the search tab
3. Click the "Show all" button for Comick
4. Gigantic stack trace appears as a result of Error 403

### Miru version

1.8.1 on Android

### Other details

Error 403 also appears when clicking on a series that has been previously favorited

I am using Android 14 on a Google Pixel 8 Pro, although I doubt that makes much difference. I've also tried using a VPN just in case my school started blocking the Comick API, and still get the error. I also attempted reinstalling the extension in case the URL was changed but the app didn't update to the new URL for some reason

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by AdalynBlack** [comment]
Upon further inspection, it seems that the URL is being generated incorrectly. As an example, the URL generated for "Futari Escape" is `https://api.comick.ccfutari-escape`. it's clear that there is a missing forward slash, but it seems that there's also some other API related sections missing from the URL, as adding that / manually didn't fix the issue

**Comment by OshekharO** [comment]
It's working properly
![Screenshot_20240207-080417_Miru](https://github.com/miru-project/repo/assets/95137948/474e9431-b57d-43bb-b614-64158ba3dbeb)

Fix for those who are facing 403 error in any extension.

Open miru -> goto miru settings -> network -> webview user agent -> replace the default value to android

**Comment by AdalynBlack** [comment]
Thanks, it seems that works
