### ISSUE TITLE
Comick 403 Error

### ISSUE THREAD

**Issue by LazyDevUserX** [miru-project/repo#218]
### Extension information

Comick

### Miru version

1.8.1

### Other details

![Screenshot (3)](https://github.com/miru-project/repo/assets/163187136/32ded6e2-abb2-45b6-a6bb-3b227ee4ad73)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Goto miru-setting and in network setting change default user-agent to android or windows try this

**Comment by LazyDevUserX** [comment]
tried using 
Mozilla/5.0 (Linux; U; Android 3.0; en-us; sdk Build/HONEYCOMB) AppleWebKit/534.13 (KHTML, like Gecko) Version/4.0 Safari/534.13

but same error

**Comment by OshekharO** [comment]
Cloudflare blocking

**Comment by GNS7** [comment]
I got around it using flaresolverr and modifying the extension file to send requests to flaresolverr, is this a viable solution for the app? I could send my code, if you guys think it's a good idea, it was my first time using javascript though so it isn't perfect, but it works.

![image](https://github.com/user-attachments/assets/cefd60a8-836f-4e94-8242-81cb299554e1)
