### ISSUE TITLE
Gogo Anime Extention Down

### ISSUE THREAD

**Issue by LazyDevUserX** [miru-project/repo#219]
### Extension information

Gogo Anime

### Miru version

1.8.1

### Other details

i think it is caused by https://goraku-api.vercel.app/anime/gogoanime because they have a outdated gogo domain name https://www1.gogoanime.bid/ instead of anitaku.io or anitaku.to

![Screenshot (4)](https://github.com/miru-project/repo/assets/163187136/e0c765de-f283-4bdc-964d-9cb634300211)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
It's an issue related to api not domain nsme. Api para aitdated for extraction will try fixing it.
