### ISSUE TITLE
Asurascans down

### ISSUE THREAD

**Issue by marc22polo** [miru-project/repo#252]
### Extension information

AsuraScans

### Steps to reproduce

When trying to open any manga from asura scans or trying to search the asura scans repo the results simply don't load.

Reinstalling the extension does not help

![Screenshot_20240730-073522](https://github.com/user-attachments/assets/6c99bfc2-8656-40d2-b995-438b1230691a)
![Screenshot_20240730-073539](https://github.com/user-attachments/assets/e78f6825-6808-420c-8505-b04916cd58e2)
![Screenshot_20240730-073558](https://github.com/user-attachments/assets/ef5308e5-f4f9-41d7-aa17-4f9bc4d74010)

### Miru version

1.8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
fixed
