### ISSUE TITLE
libvio无法播放

### ISSUE THREAD

**Issue by TangBaoY** [miru-project/repo#260]
### Extension information

libvio

### Steps to reproduce

![Screenshot_2024-09-03-19-54-42-42](https://github.com/user-attachments/assets/ff1334b5-743a-4205-bfa5-f069bf8de103)

### Miru version

1.8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Got this while opening for details or watch?

**Comment by TangBaoY** [comment]
> Got this while opening for details or watch?

Unable to watch

**Comment by OshekharO** [comment]
This extension maintained by @appdevelpo, he will fix it when he gets free time.
