### ISSUE TITLE
mangacopy.comic Broken

### ISSUE THREAD

**Issue by iris1598** [miru-project/repo#276]
### Extension information

mangacopy.comic

### Steps to reproduce

download mangacopy.comic extension
open any comic/search any comic
throws error/No search results found.
![QQ20240925-140311](https://github.com/user-attachments/assets/3fb2d610-0d11-4fc9-a3f4-52b2f2fed03c)

### Miru version

1.8.1

### Other details

URIError: expecting hex digit
    at decodeURIComponent (native)
    at decodeUnicode (<eval>:26)
    at detail (<eval>:73)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by iris1598** [comment]
@hualiong 为什么移除了加密和解密的代码，这好像使得拷贝漫画这个插件不工作了。

**Comment by hualiong** [comment]
额，原来会导致不工作吗？因为Miru有内置CryptoJS库，所以不需要在拓展中再次引入，我之前写的拓展都是可以正常运行😥
