### ISSUE TITLE
Mangakatana latest page can't use pagination

### ISSUE THREAD

**Issue by GNS7** [miru-project/repo#282]
### Extension information

MangaKatana

### Steps to reproduce

Open latest, try to scroll to load new titles, nothing happens.

### Miru version

1.8.1

### Other details

I noticed the extension was not parsing the html correctly, because on the debug menu some items were just cut out, so I fixed that, now it works fine in the debug menu, but extension still won't load new manga, because it is not using pagination correctly, so it doesn't request the next page.

![image](https://github.com/user-attachments/assets/8cb7e851-b7ff-4b92-9807-282b2845fc0e)

Debug menu:

![image](https://github.com/user-attachments/assets/201cc1b8-2b32-4595-9acf-90d3d2edf873)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
It's working perfectly fine for me
