### ISSUE TITLE
Asura scans

### ISSUE THREAD

**Issue by marc22polo** [miru-project/repo#327]
### Extension information

AsuraScans

### Steps to reproduce

Whenever I try to open a manga from asura scans it starts loading then just shows a blank page and the page counter says 1/0

![Screenshot_20241126-190542](https://github.com/user-attachments/assets/a1b374c5-85b5-4dfa-90a9-d1fee24f8381)

Steps to reproduce:
1. Open any manga on Asura scans
2. Click on any chapter

Refavouriting doesn't help and neither does opening the manga directly from the asurascans tab (or from favourites).

### Miru version

1.8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by YuJunZhiXue** [comment]
I found the problem. Due to the update of the website, the data is stored in the script, so the data needs to be retrieved. If you are in a hurry, please replace the following code directly, otherwise wait for the author to update



我找到了问题的所在，由于网站更新，导致数据存在了script中这样需要重新获取数据，如果你着急看的话，请你直接替换如下代码即可，否则就等作者更新

```
  async watch(url) {
    console.log(url + " url");

    const res = await this.request("", {
      headers: {
        "Miru-Url": "https://asuracomic.net/series/" + url,
        referer: "https://asuracomic.net/",
        origin: "https://asuracomic.net",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36",
      },
    });
    const regex = /<script>(.*?)\<\/script>/gs;
    const matches = res.match(regex);
    const pageRegex = /\\"pages\\":\[(.*?)\]/gs;
    const pageMatches = matches.join("").match(pageRegex);
    console.log(pageMatches + "pageMatches");
    const httpRegex = /https:\/\/[^\\]+/g;
    const httpMatches = pageMatches.join("").match(httpRegex);
    console.log(httpMatches.length + "httpMatches.length");
    console.log(httpMatches + "httpMatches");

    return {
      urls: httpMatches,
    };
  }
  ```
  
  
  
![image](https://github.com/user-attachments/assets/bdd4bbdc-97ee-4c9b-a9f2-779916083b2d)
