### ISSUE TITLE
如何提交新的源到仓库？（How to submit new sources to the repository?）

### ISSUE THREAD

**Issue by YuJunZhiXue** [miru-project/repo#328]
### Extension information

“gzhanmh”

### Steps to reproduce

请告知我一下如何提交至仓库，因为我第一次尝试此功能

### Miru version

“1.8.0”

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Fork this repo - Create the extension - submit pull request

**Comment by YuJunZhiXue** [comment]
> Fork this repo - Create the extension - submit pull request

请问是直接git此项目，还是将此项目fork到我的仓库，
如果是fork到我的仓库，我怎么提交到此仓库呢

**Comment by YuJunZhiXue** [comment]
> Fork this repo - 创建扩展 - 提交拉取请求

您好我已经将request   pull给仓库里请通过一下请求
