### ISSUE TITLE
我已经添加新的扩展请求通过

### ISSUE THREAD

**Issue by YuJunZhiXue** [miru-project/repo#332]
### Source name

gufengmh

### Source URL

https://www.gufengmh.com

### Other details

以上传至requests，请求通过申请 @OshekharO

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by YuJunZhiXue** [comment]
修改了AsuraScans不显示问题， 我后期可能会添加很多漫画源，所以请求快速通过一下

**Comment by OshekharO** [comment]
Sure go ahead ☺️

**Comment by OshekharO** [comment]
#331
