### ISSUE TITLE
[Invidious] Failed to open the `URL`

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#59]
### Extension information

Invidious

### Steps to reproduce

1. Open the Invidious in search
2. For example, open the video say (Tyla - Water (Official Music Video) or Doja Cat - Paint The Town Red (Official Video))
3. click to play the video
4. then error message will show `Failed to open the {URL}`

### Miru version

1.7.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by bachig26** [comment]
I'm actually seeing that a lot of videos can't be played in my 1st few minutes of using the Invidious extension.

**Comment by OshekharO** [comment]
> I'm actually seeing that a lot of videos can't be played in my 1st few minutes of using the Invidious extension.

That's the issue due to current api try going back and open again if not do 2 to 3 time it should work

**Comment by bachig26** [comment]
@OshekharO I have another question, is there a guide available for creating the extension?

**Comment by OshekharO** [comment]
> @OshekharO I have another question, is there a guide available for creating the extension?

Hmm yes there is but not complete infact you may start creating extension by taking any existing extension as a base.

As for invidious I will try finding another api for stream

**Comment by OshekharO** [comment]
Yes Now it's working ☺️, so most probably Google is limiting it.
