### ISSUE TITLE
agefans.tv and cocomanhua

### ISSUE THREAD

**Issue by ghost** [miru-project/repo#63]
### Extension information

comic

### Steps to reproduce

Please support agefans.tv and cocomanhua!

### Miru version

1.6

### Other details

https://github.com/miru-project/miru-app/issues/88

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ghost** [comment]
FYI:https://github.com/HDYOU/autoCI-cocomanga

**Comment by SendHX** [comment]
可以出个TV版本吗？
