### ISSUE TITLE
大佬可以加入colamanga漫画和yanaifei吗

### ISSUE THREAD

**Issue by Joackk** [miru-project/repo#71]
### Source name

colamanga漫画、鸭奈飞影视

### Source URL

https://www.colamanga.com、https://yanaifei.tv

### Package type

漫画、影视

### Source language

zh

### Other details

colamanga漫画：https://www.colamanga.com
鸭奈飞影视：https://yanaifei.tv

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by appdevelpo** [comment]
鸭奈飞影视幾乎完成了，但目前用戶需要輸入cookie 才可以使用

**Comment by Joackk** [comment]
> 鸭奈飞影视幾乎完成了，但目前用戶需要輸入cookie 才可以使用

x需要cookie吗？但我用它时候都没有登陆啊？

**Comment by appdevelpo** [comment]
主要是因為cloudfare如果不加cookie 的話會被拒絕

**Comment by Joackk** [comment]
> 主要是因為cloudfare如果不加cookie 的話會被拒絕

soga，这个cookie是校验用吗？我用的时候都并没有登录，那直接拿一个她发给浏览器的cookie内置进去可以吗？

**Comment by Joackk** [comment]
> 主要是因為cloudfare如果不加cookie 的話會被拒絕

因为用的时候也没有登陆什么的，所以这个cookie应该用一个都可以把？毕竟也不是用来校验用户的

**Comment by appdevelpo** [comment]
我已經pr，可以試試，如果不行的話可以試gimy，少了cloudfare而且片源跟鴨奈飛類似

**Comment by Joackk** [comment]
> 我已經pr，可以試試，如果不行的話可以試gimy，少了cloudfare而且片源跟鴨奈飛類似

soga，感谢大佬，是直接在仓库里装吗？仓库里似乎没有找到

**Comment by appdevelpo** [comment]
審核中

**Comment by appdevelpo** [comment]
真的抱歉，最後因為cloudfare 的關係最後還是沒法pr，如果真的想要就去這載吧，只要沒被擋，應該都是有功能的，擴展的設定可以調整cookie
https://github.com/appdevelpo/trashbin/blob/main/yanaifei.tv.js

**Comment by Joackk** [comment]
> 真的抱歉，最後因為cloudfare 的關係最後還是沒法pr，如果真的想要就去這載吧，只要沒被擋，應該都是有功能的，擴展的設定可以調整cookie https://github.com/appdevelpo/trashbin/blob/main/yanaifei.tv.js

万分感谢，大佬太客气了，感谢感谢

**Comment by Joackk** [comment]
> 真的抱歉，最後因為cloudfare 的關係最後還是沒法pr，如果真的想要就去這載吧，只要沒被擋，應該都是有功能的，擴展的設定可以調整cookie https://github.com/appdevelpo/trashbin/blob/main/yanaifei.tv.js

可以正常使用，感谢大佬
