### ISSUE TITLE
[KimCartoon] Backdrop/ (also posters) doesn't display in all titles

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#78]
### Extension information

KimCartoon

### Miru version

1.7.2

### Other details

Some of the titles show the backdrops correctly and some just displays the background color of the poster for backdrops and some backdrops are just blank.

![miru_WERZhjO2wM](https://github.com/miru-project/repo/assets/96393348/b41cc4fe-0699-4b15-8f5d-862489694a40)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Have you checked whether the backdrop is available on the website or not?

**Comment by OshekharO** [comment]
![Screenshot_2023-10-22-15-36-19-88_724c77a6924735f59ad9bef5bae520c3](https://github.com/miru-project/repo/assets/95137948/bbe8686b-878d-439b-84f3-d3b736e8bd58)

I am not facing any such issues, check your internet connection.

**Comment by bachig26** [comment]
@OshekharO it's not a problem with the internet connection, which i checked and it's just problem with fetching them to the app i guess.

here are the some screenshots around the homepage, from search page: flixhq, kimcartoon.
please have a look if it can be fixed.

| Position              | Screenshots |
| :----------------: | :----: |
| Homepage        | ![miru_RwBvbggpGo](https://github.com/miru-project/repo/assets/96393348/22848a31-6f05-4b28-bd5a-273c46c4effc) |
| Search    | ![miru_vixJdi3OkC](https://github.com/miru-project/repo/assets/96393348/6630a37c-d453-4bda-9937-049b6a262af8) |
| FlixHQ (Extension)           | ![miru_vWM1iCL05X](https://github.com/miru-project/repo/assets/96393348/52f2fa30-0c9a-460d-8664-ced8335b446a) |
| KimCartoon (SearchTerm: Kim Possible)           | ![miru_wpbk0L3the](https://github.com/miru-project/repo/assets/96393348/09e94264-2f92-4a94-9145-92458752a3aa) |
| KimCartoon (insideTitle)           | ![miru_AD2mbXIhYb](https://github.com/miru-project/repo/assets/96393348/91bb5ad9-f941-4c8a-844c-a49c5a2d1a9c) |
