### ISSUE TITLE
FlixHQ: Extension missing error, poster issue and other

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#83]
### Extension information

FlixHQ

### Miru version

1.7.2

### Other details

@OshekharO is it possible to move the FlixHQ from consumet api to the website scraper as other because i getting the Extension missing error few times a day and need to wait sometime to get it back online.
also this might possible save from some issues like the connection interruption, ratelimit from api, backdrop and poster issue.

also one time, the player got stutter a lot and i got back after few hours but it maybe a problem for long run. (for this i'm not sure if it's issue with extension or player)

this screenshots which i have commented on the closed issue #78 after experiencing similar issue.
| Position              | Screenshots |
| :----------------: | :----: |
| Search    | ![miru_vixJdi3OkC](https://github.com/miru-project/repo/assets/96393348/6630a37c-d453-4bda-9937-049b6a262af8) |
| FlixHQ (Extension)           | ![miru_vWM1iCL05X](https://github.com/miru-project/repo/assets/96393348/52f2fa30-0c9a-460d-8664-ced8335b446a) |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Extension missing error didn't happened with me and second thing entirely using different approach for it is troublesome and domain keeps on changing so for now it's good, will see if it require changes later.
