### ISSUE TITLE
Movieku: Failed to install error

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#89]
### Extension information

Movieku

### Steps to reproduce

1. Open the `Extension Repository`.
2. Click the `Install` button on the Movieku Extension.
3. The Failed to install extension error appears.

### Miru version

1.7.2

### Other details

![miru_vdGRNOioZL](https://github.com/miru-project/repo/assets/96393348/5ad21e5e-e54d-4d5e-8fbc-6757dd37280d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
@appdevelpo
