### ISSUE TITLE
Turkish123: change to correct `latest`

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#91]
### Extension information

Turkish123

### Miru version

1.7.2

### Other details

@OshekharO 

`latest`: /series-list/  ===>  /episodes-list/

I can see when opening with this above change resulting in breaking things like the backdrop and tv series info like cast, description and also shows other buttons like the Option 1, etc,. since it doesn't open the title page instead opens the episode page.

can you able to see if this can be achieved by getting the url from the `div.header-pad` just for the contents opened via `latest`?
example => view-source:https://www2.turkish123.org/ates-kuslari-episode-28/ (line 293)

| Screenshot | Description |
| :------: | :------: |
| ![notepad++_TpsKzCG8oW](https://github.com/miru-project/repo/assets/96393348/0459be44-2b7f-423f-acaf-95eee92d7c29) | from App View of the Search section |
| ![mercury_bClGt64nCb](https://github.com/miru-project/repo/assets/96393348/86417512-8585-4e6a-b959-0a89155e4403) | Series List (current used as latest in extension) |
| ![mercury_u6B1m3w0cG](https://github.com/miru-project/repo/assets/96393348/65234b6a-fecb-4ac6-b2ed-363ced990cb2) | Latest Episodes (correct latest in webpage) |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Currently I don't think it's suitable because it will break the whole extension, will probably try something later on but for now it's big no.
