### ISSUE TITLE
sakura: 樱花动漫插件只能观看第一集

### ISSUE THREAD

**Issue by 2756481637** [miru-project/repo#94]
### Extension information

sakura

### Steps to reproduce

通过樱花动漫插件打开任意一部的除第一集以外的内容, 都会出现报错 `TypeError: cannot read property '1' of null at watch (<eval>:127)` 

### Miru version

1.7.2

### Other details

在调试过程中, 我发现第127行的
``` js
const m3mu8_url = "https://danmu.yhdmjx.com/m3u8.php?url="+res.match(/"link_pre":"","url":"(.*?)"/)[1];
```
可能是罪魁祸首

这行代码会在数据`res`中匹配相应的字符串, 并将字段`url`中的数据提取出来, 这在第一集中可以很好地工作, 但是在其他集数中, 由于`link_per`字段并不为空, 这行代码无法匹配到它需要匹配到的内容, 并导致播放失败

当我将这行代码改为
```js
const m3mu8_url = "https://danmu.yhdmjx.com/m3u8.php?url="+res.match(/"link_pre":".*","url":"(.*?)"/)[1];
```
时, 它又可以很好地工作

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
If you know how to fix it just make an pr I will review and merge it for now I will just apply your mentioned changes as I can see it's working.
