### ISSUE TITLE
SFlix: 1. search doesn't work | 2. few titles can't be played | 3. taking too long to load | 4. issue with loading sflix latest page

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#96]
### Extension information

sflix

### Steps to reproduce

1. open the sflix in search
2. enter any title (example: the good witch)
3. the following error no.1 (search results not shown) occurs

--------------
1. open the sflix in search
2. click a title (example: Daily Does of Sunshine)
3. select episode 2
4. the following error no.2 occurs

### Miru version

1.7.2

#### 1. search results not shown
```
DioException [bad response]: The request returned an invalid status code of 400.
#0      new JSError (package:flutter_js/quickjs/object.dart:92)
#1      _dartToJs (package:flutter_js/quickjs/wrapper.dart:60)
#2      _JSFunction._invoke.<anonymous closure> (package:flutter_js/quickjs/object.dart:174)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#7      new List.of (dart:core-patch/array_patch.dart:47)
#8      SetBase.toList (dart:collection/set.dart:119)
#9      _JSFunction._invoke (package:flutter_js/quickjs/object.dart:176)
#10     _JSFunction.invoke (package:flutter_js/quickjs/object.dart:155)
#11     _dartToJs.<anonymous closure> (package:flutter_js/quickjs/wrapper.dart:86)
#12     _RootZone.runUnary (dart:async/zone.dart:1661)
#13     _FutureListener.handleError (dart:async/future_impl.dart:174)
#14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#15     Future._propagateToListeners (dart:async/future_impl.dart:873)
#16     Future._completeError (dart:async/future_impl.dart:649)
#17     _RootZone.runBinary (dart:async/zone.dart:1666)
#18     _FutureListener.handleError (dart:async/future_impl.dart:171)
#19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#20     Future._propagateToListeners (dart:async/future_impl.dart:873)
#21     Future._completeError (dart:async/future_impl.dart:649)
#22     _SyncCompleter._completeError (dart:async/future_impl.dart:60)
#23     _Completer.completeError (dart:async/future_impl.dart:26)
#24     Future.any.onError (dart:async/future.dart:620)
#25     _RootZone.runBinary (dart:async/zone.dart:1666)
#26     _FutureListener.handleError (dart:async/future_impl.dart:171)
#27     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#28     Future._propagateToListeners (dart:async/future_impl.dart:873)
#29     Future._completeError (dart:async/future_impl.dart:649)
#30     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:550)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

2. error in video player
```
tcp: ffurl_read returned 0xffffff76
```

3. issue with loading sflix latest page
```
Error: not implement createFilter
    at createFilter (<eval>:143)
    at <anonymous> (<eval>)
    at stringify (<eval>:166)
    at <eval> (<eval>)
```

@appdevelpo also sometimes, i get `Null type error` while opening the title in video player and the content is in the webpage which I have checked.
also regarding the `taking too long to load` comment, it's too slow than playing via the browser, please have a look into this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Everything is working except for query which contains space inbetween. Use 1.1.1.1 dns by cloudflare checkout ps.

**Comment by OshekharO** [comment]
There are some provider's which are blocking some isp or more specifically Indian IP that's why I mentioned in main repo that dns feature is a must

**Comment by bachig26** [comment]
> There are some provider's which are blocking some isp or more specifically Indian IP that's why I mentioned in main repo that dns feature is a must

No bro, I'm in Germany and I use sflix.to almost every day to watch and haven't had any issue via browser, i had no problem with my isp, even while typing this comment it works better at browser for me.
🤔

**Comment by appdevelpo** [comment]
First, createFilter will show error if you didn't use "createFilter" in the extension. It doesn't affect the extension functioning. Second, the loading takes time because I try to get all different m3u8 resolution link  in the movie. It means that besides I get movie "auto" link,I need to send resquest to "auto" link to get "1080","720"...etc.

**Comment by bachig26** [comment]
> First, createFilter will show error if you didn't use "createFilter" in the extension. It doesn't affect the extension functioning. Second, the loading takes time because I try to get all different m3u8 resolution link in the movie. It means that besides I get movie "auto" link,I need to send resquest to "auto" link to get "1080","720"...etc.

okay got it. 👍

@appdevelpo can you see what this is `tcp: ffurl_read returned 0xffffff76` as mentioned above.
whenever i see this msg popup, the video gets laggy like how the mpv player gets when you see this error `Audio device underrun detected.`.
