### ISSUE TITLE
[NFSW] ParadiseHill

### ISSUE THREAD

**Issue by bachig26** [miru-project/repo#98]
### Source name

ParadiseHill

### Source URL

https://en.paradisehill.cc

### Package type

bangumi

### Source language

en

### Other details

Reference:

from CloudStream: https://github.com/hexated/cloudstream-extensions-hexated/blob/master/Paradisehill/src/main/kotlin/com/hexated/Paradisehill.kt

from a Kodi repo: https://github.com/dobbelina/repository.dobbelina

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
I think current nsfw extensions are enough or not? 😂

**Comment by bachig26** [comment]
> I think current nsfw extensions are enough or not? 😂

I know there are some but it mostly uses the torrent/p2p and I made to request that only hosted by cloud servers.

**Comment by OshekharO** [comment]
> > I think current nsfw extensions are enough or not? 😂
> 
> I know there are some but it mostly uses the torrent/p2p and I made to request that only hosted by cloud servers.

Sure I will try to add, but only 1 or 2 nsfw extension made by me are based on torrent else all are hosted one.

**Comment by bachig26** [comment]
> 
> Sure I will try to add, but only 1 or 2 nsfw extension made by me are based on torrent else all are hosted one.

okay, i'll check again in the list.

**Comment by OshekharO** [comment]
> > Sure I will try to add, but only 1 or 2 nsfw extension made by me are based on torrent else all are hosted one.
> 
> okay, i'll check again in the list.

Try sunporno, eroticmv, javhd + all other hentai extension
